version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules

  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
        name: test
        command: 'react-scripts test --env=jsdom --testResultsProcessor="jest-junit-reporter"'
      - store_artifacts:
        path: test-report.xml
        prefix: tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
