version: '3'

networks:

  fabric: {}

services:

  clock:

    build: ./clock
    networks:
      - fabric
    ports:
      - 4567:4567

  sidecar:

    build: ./sidecar
    networks:
      - fabric
    ports:
      - 7080:7080
      - 7081:7081

  edge:

    build: ./edge
    networks:
      - fabric
    ports:
      - 8080:8080
      - 8081:8081
